// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import{NuqsAdapter} from "nuqs/adapters/next";

// import { TRPCReactProvider } from "@/trpc/client";

// import "./globals.css";
// import { Toaster } from "@/components/ui/sonner";

// const inter = Inter({
 
//   subsets: ["latin"],
// });



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <NuqsAdapter>
//     <TRPCReactProvider>
//       <html lang="en">
//         <body
//           className={`${inter.className}  antialiased`}
//         >
//           <Toaster/>
//           {children}
//         </body>
//       </html>
//     </TRPCReactProvider>
//     </NuqsAdapter>
//   );
// }
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NuqsAdapter } from "nuqs/adapters/next";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MeetAI",
  description: "AI-powered meeting assistant",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <NuqsAdapter>
          <TRPCReactProvider>
            <Toaster />
            {children}
          </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
